### ISSUE TITLE
Missing Color Management

### ISSUE THREAD

**Issue by maf** [damko/gnome3-plus-i3#5]
I have tried your code and works fine however I cannot figure out how to bring back color profiles for display.
In gnome3 'colormgr get-devices' gives me for instance displays and I can check if my ICC profiles are consistent simply typing 'darktable-cmstest'.
Now after upgrading to ubuntu 18.04 I cannot get this right with i3. It's all empty. Worked fine with 16.04 and plain i3 (with exec --no-startup-id unity-settings-daemon).

I have noticed that with full gnome env on ubuntu I have a lot of gnome-settings-daemon/* owned by me and in i3 plus gnome3 there is none.

I worked with your code a while doing some researching with no luck.
Got any ideas?

**Comment by damko** [comment]
I'm totally ignorant about ICC profiles (miscalibrated colors don't not affect my job) but let me try to help:
open a terminal and type

    env XDG_CURRENT_DESKTOP=GNOME gnome-control-center

(this is the only way I've found to make gnome-control-center work in I3)

Then click on devices: you should be able to see this:

![screenshot from 2018-08-06 17-16-07](https://user-images.githubusercontent.com/1107588/43725446-da206a16-999c-11e8-9226-a3cd1c31e07c.png)

I see the menu "Color" which only lists printers. When I click on Displays, unfortunately, I get "Could not get screen information" and I don't know why. Can you see something in there?

**Comment by damko** [comment]
btw, if I run `colormgr get-devices` in i3 I get back the exact same list of devices that you can see in the screenshot.
Try to prefix the command with "env XDG_CURRENT_DESKTOP=GNOME"

**Comment by maf** [comment]
So something is broken in my env. I got null list and gnome-control-center is also empty even for displays.

**Comment by maf** [comment]
@damko in your i3 session do you own /usr/lib/gnome-settings/daemon/* processes?
In original ubuntu session there are 2 sets. One own by gdm and one by me. In i3+gnome3 there are only gdm owned processes.

**Comment by damko** [comment]
Debian-+ 23417  0.0  0.2 617788 33672 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-xsettings
Debian-+ 23419  0.0  0.0 273352  6136 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-a11y-settings
Debian-+ 23420  0.0  0.1 466728 30100 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-clipboard
Debian-+ 23423  0.0  0.2 808248 33968 tty1     Sl+  04:39   0:01 /usr/lib/gnome-settings-daemon/gsd-color
Debian-+ 23424  0.0  0.1 371776 16840 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-datetime
Debian-+ 23425  0.0  0.0 273260  5228 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-housekeeping
Debian-+ 23426  0.0  0.2 616636 32564 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-keyboard
Debian-+ 23430  0.0  0.2 1133044 34380 tty1    Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-media-keys
Debian-+ 23433  0.0  0.0 195004  5276 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-mouse
Debian-+ 23437  0.0  0.2 989088 36224 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-power
Debian-+ 23440  0.0  0.0 246520  8996 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-print-notifications
Debian-+ 23442  0.0  0.0 195028  4808 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-rfkill
Debian-+ 23443  0.0  0.0 268744  4960 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy
Debian-+ 23448  0.0  0.0 294320 10772 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-sharing
Debian-+ 23452  0.0  0.0 367276  9704 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-smartcard
Debian-+ 23453  0.0  0.0 338412  8460 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-sound
Debian-+ 23458  0.0  0.2 549852 35336 tty1     Sl+  04:39   0:00 /usr/lib/gnome-settings-daemon/gsd-wacom
**damko    26680  0.0  0.0   4396   836 ?        S    13:17   0:00 /bin/sh -c /usr/lib/gnome-settings-daemon/gsd-xsettings**
**damko    26685  0.0  0.1 482440 23312 ?        Sl   13:17   0:00 /usr/lib/gnome-settings-daemon/gsd-xsettings**

I only own gsd-xsettings

Do you run `exec --no-startup-id /usr/lib/gnome-settings-daemon/gsd-xsettings` at i3 startup?

**Comment by damko** [comment]
this is what I run at i3 startup

exec compton --config ~/.config/compton.conf
exec gnome-screensaver &                               # starts gnome3 screensaver daemon
exec --no-startup-id xautolock -time 5 -locker "gnome-screensaver-command -a" & #runs screensaver after 5 minutes idle
exec --no-startup-id /usr/lib/gnome-settings-daemon/gsd-xsettings
exec gnome-terminal --title="terminal4scratchpad" --hide-menubar
