### ISSUE TITLE
Assumption that file ~/.config/i3/config contains "exits i3"

### ISSUE THREAD

**Issue by ghost** [damko/gnome3-plus-i3#6]
I don't have this (Ubuntu 18.04 initially installed with Unity, then Gnome 3 installed afterwards).
If this only supports Ubuntu with Gnome 3 installed out of the box, can you make this clearer please, or alternatively explain what dependencies I need to have installed (beyond those already mentioned, which I did indeed install), to get this to work? Many thanks.

**Comment by damko** [comment]
hello Andy, that's weird. I don't use Ubuntu so I don't know what's the default config file added in the package. However the user must have a way to exit i3, right? So there must be something.

This is the bit I'm referring to:

    # exits i3 (logs you out of your X session)
    bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

Try to grep your config file for "i3-nagbar"
